name: Check PubMed source
on:
  workflow_dispatch:

jobs:
  calculate-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup uv
        uses: astral-sh/setup-uv@v7.1.4

      - name: Fetch and display recent PubMed articles
        env:
          NCBI_EMAIL: ${{ secrets.NCBI_EMAIL }}
          NCBI_API_KEY: ${{ secrets.NCBI_API_KEY }}
        run: uv run scripts/check_pubmed.py
